"""
compliance/playbooks.py — Actionable Remediation Playbook Generator.

Generates deterministic, context-specific remediation playbooks as
Ansible-compatible YAML tasks for each quantum-vulnerable asset.

Playbook tiers:
  • CRITICAL  — Immediate emergency order: HSM re-keying, emergency ACME cert rotation
  • HIGH      — Planned migration: TLS config hardening, library upgrade
  • MEDIUM    — Scheduled: configuration audit, hybrid KEM enablement
  • LOW       — Informational: monitoring, future-proofing notes

Human-in-the-Loop gate:
  Critical-tier playbooks MUST obtain approval via ServiceNow or Jira ticket
  before execution. The gate stub calls the external REST API and blocks
  until the ticket transitions to "Approved" state.
"""

from __future__ import annotations

import enum
import textwrap
import uuid
from datetime import datetime
from typing import Any

import structlog
import yaml
from pydantic import BaseModel, ConfigDict, Field

from app.compliance.labeling import (
    AlgorithmFinding,
    ComplianceLabelResult,
    QuantumLabel,
)

logger = structlog.get_logger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Enums & Schemas
# ─────────────────────────────────────────────────────────────────────────────

class PlaybookTier(str, enum.Enum):
    CRITICAL = "critical"
    HIGH     = "high"
    MEDIUM   = "medium"
    LOW      = "low"


class ApprovalStatus(str, enum.Enum):
    PENDING   = "pending"
    APPROVED  = "approved"
    REJECTED  = "rejected"
    NO_GATE   = "no_gate"     # Non-critical playbooks; no approval required


class AnsibleTask(BaseModel):
    """A single Ansible task dict (conforms to Ansible task YAML schema)."""
    name:        str
    module_data: dict[str, Any]   # The Ansible module name is a key
    tags:        list[str] = Field(default_factory=list)
    notify:      list[str] | None = None
    when:        str | None = None

    def to_ansible_dict(self) -> dict[str, Any]:
        """Serialise to a valid Ansible task dict."""
        task: dict[str, Any] = {"name": self.name}
        task.update(self.module_data)
        if self.tags:
            task["tags"] = self.tags
        if self.notify:
            task["notify"] = self.notify
        if self.when:
            task["when"] = self.when
        return task


class RemediationPlaybook(BaseModel):
    """A complete Ansible-compatible playbook for one asset."""
    model_config = ConfigDict(from_attributes=True)

    playbook_id:     str = Field(default_factory=lambda: str(uuid.uuid4()))
    asset_id:        uuid.UUID | None = None
    host:            str | None = None
    tier:            PlaybookTier
    title:           str
    description:     str
    algorithms_targeted: list[str]
    ansible_tasks:   list[AnsibleTask]
    approval_status: ApprovalStatus = ApprovalStatus.NO_GATE
    approval_ticket: str | None = None   # ServiceNow/Jira ticket ID
    generated_at:    datetime = Field(default_factory=datetime.utcnow)
    estimated_effort_hours: float = 0.0

    def to_ansible_yaml(self) -> str:
        """Export the playbook as a complete Ansible YAML playbook string."""
        play = {
            "name": self.title,
            "hosts": self.host or "target_host",
            "become": True,
            "vars": {
                "playbook_id": self.playbook_id,
                "asset_id": str(self.asset_id) if self.asset_id else "unknown",
                "generated_at": self.generated_at.isoformat(),
            },
            "tasks": [task.to_ansible_dict() for task in self.ansible_tasks],
        }
        header = textwrap.dedent(f"""\
            # ═══════════════════════════════════════════════════════════════════
            # PQC Remediation Playbook — {self.tier.value.upper()}
            # Generated by Quantum-Proof Systems Scanner
            # Playbook ID : {self.playbook_id}
            # Asset       : {self.host or self.asset_id}
            # Approval    : {self.approval_status.value}
            # Ticket      : {self.approval_ticket or 'N/A'}
            # ═══════════════════════════════════════════════════════════════════
            """)
        return header + yaml.dump([play], default_flow_style=False, sort_keys=False)


# ─────────────────────────────────────────────────────────────────────────────
# Task Template Library
# ─────────────────────────────────────────────────────────────────────────────

def _task_update_openssl(host: str, target_algo: str) -> AnsibleTask:
    return AnsibleTask(
        name=f"Update OpenSSL to support PQC hybrid KEM on {host}",
        module_data={
            "ansible.builtin.package": {
                "name": ["openssl", "liboqs", "oqs-provider"],
                "state": "latest",
            }
        },
        tags=["pqc", "openssl", "phase1"],
        notify=["Restart nginx", "Restart apache2"],
    )


def _task_configure_tls_policy(cipher_policy: str = "PQC_HYBRID") -> AnsibleTask:
    return AnsibleTask(
        name=f"Apply TLS crypto policy: {cipher_policy}",
        module_data={
            "ansible.builtin.command": {
                "cmd": f"update-crypto-policies --set {cipher_policy}",
                "creates": f"/etc/crypto-policies/state/current",
            }
        },
        tags=["tls", "crypto-policy", "phase1"],
    )


def _task_nginx_tls_hardening(host: str) -> AnsibleTask:
    return AnsibleTask(
        name=f"Harden nginx TLS configuration on {host}",
        module_data={
            "ansible.builtin.lineinfile": {
                "path": "/etc/nginx/nginx.conf",
                "regexp": "^(\\s*ssl_protocols)",
                "line": "    ssl_protocols TLSv1.3;  # TLS 1.2 disabled per PQC policy",
                "backrefs": True,
            }
        },
        tags=["nginx", "tls", "hardening"],
        notify=["Reload nginx"],
    )


def _task_disable_deprecated_ciphers() -> AnsibleTask:
    return AnsibleTask(
        name="Disable deprecated cipher suites (RC4, 3DES, SHA-1, export-grade)",
        module_data={
            "ansible.builtin.template": {
                "src":  "templates/openssl_no_deprecated.cnf.j2",
                "dest": "/etc/ssl/openssl.cnf",
                "mode": "0644",
            }
        },
        tags=["ciphers", "hardening", "critical"],
        notify=["Restart sshd", "Restart stunnel"],
    )


def _task_rotate_certificate(host: str) -> AnsibleTask:
    return AnsibleTask(
        name=f"Rotate TLS certificate to ML-DSA-65 on {host}",
        module_data={
            "community.crypto.acme_certificate": {
                "account_email":    "pki-ops@pnb.co.in",
                "csr":              f"/etc/ssl/certs/{host}.csr",
                "dest":             f"/etc/ssl/certs/{host}.crt",
                "acme_directory":   "https://acme-v02.api.letsencrypt.org/directory",
                "acme_version":     2,
                "challenge":        "dns-01",
                "remaining_days":   30,
            }
        },
        tags=["certificate", "pki", "rotation"],
    )


def _task_enable_hybrid_kem(host: str) -> AnsibleTask:
    return AnsibleTask(
        name=f"Enable X25519Kyber768 hybrid KEM on {host}",
        module_data={
            "ansible.builtin.blockinfile": {
                "path":   "/etc/nginx/conf.d/tls.conf",
                "block":  (
                    "ssl_conf_command Ciphersuites "
                    "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256;\n"
                    "ssl_conf_command Groups x25519kyber768:x25519:secp256r1;"
                ),
                "marker": "# {mark} PQSS HYBRID KEM BLOCK",
            }
        },
        tags=["kem", "hybrid", "tls13"],
        notify=["Reload nginx"],
    )


def _task_hsm_rekey(host: str, algorithm: str) -> AnsibleTask:
    return AnsibleTask(
        name=f"Trigger HSM re-keying for {algorithm} on {host} (CRITICAL)",
        module_data={
            "ansible.builtin.uri": {
                "url":        "https://{{ hsm_api_endpoint }}/v1/rekey",
                "method":     "POST",
                "body_format": "json",
                "body": {
                    "host":      host,
                    "algorithm": "ML-KEM-1024",
                    "key_label": f"pqc_{host.replace('.', '_')}_2026",
                    "reason":    f"PQC migration from {algorithm}",
                },
                "headers": {"Authorization": "Bearer {{ hsm_api_token }}"},
                "status_code": [200, 201],
            }
        },
        tags=["hsm", "critical", "rekey"],
        when="approval_status == 'approved'",
    )


def _task_verify_pqc_handshake(host: str) -> AnsibleTask:
    return AnsibleTask(
        name=f"Verify PQC handshake on {host} using sslyze",
        module_data={
            "ansible.builtin.command": {
                "cmd": f"sslyze --json_out=/tmp/sslyze_{host}.json {host}:443"
            }
        },
        tags=["verify", "sslyze", "post-deploy"],
    )


def _task_send_notification(playbook_id: str, tier: str) -> AnsibleTask:
    return AnsibleTask(
        name="Send Slack/email notification on completion",
        module_data={
            "community.general.slack": {
                "token":    "{{ slack_bot_token }}",
                "msg":      f"✅ PQC Playbook *{playbook_id}* [{tier.upper()}] completed on `{{{{ inventory_hostname }}}}`.",
                "channel":  "#pqc-alerts",
                "icon_emoji": ":lock:",
            }
        },
        tags=["notification", "slack"],
    )


# ─────────────────────────────────────────────────────────────────────────────
# Playbook Generator
# ─────────────────────────────────────────────────────────────────────────────

class RemediationPlaybookGenerator:
    """
    Generates Ansible-compatible YAML remediation playbooks from compliance labels.

    Usage::

        gen = RemediationPlaybookGenerator()
        playbooks = gen.generate(compliance_result)
        for pb in playbooks:
            print(pb.to_ansible_yaml())
    """

    def _determine_tier(self, result: ComplianceLabelResult) -> PlaybookTier:
        """Map compliance label + deprecated count to playbook tier."""
        if result.deprecated_count > 0:
            return PlaybookTier.CRITICAL
        if result.quantum_label == QuantumLabel.QUANTUM_VULNERABLE:
            return PlaybookTier.HIGH
        if result.quantum_label == QuantumLabel.PQC_READY:
            return PlaybookTier.MEDIUM
        return PlaybookTier.LOW

    def _build_tasks(
        self,
        host: str,
        tier: PlaybookTier,
        findings: list[AlgorithmFinding],
    ) -> tuple[list[AnsibleTask], float]:
        """Build task list and effort estimate for the given tier."""
        tasks: list[AnsibleTask] = []
        effort = 0.0

        deprecated_algos = [f.algorithm for f in findings if f.is_deprecated]
        vulnerable_algos = [f.algorithm for f in findings if not f.is_approved and not f.is_hybrid]

        if tier == PlaybookTier.CRITICAL:
            tasks.append(_task_disable_deprecated_ciphers())
            for algo in deprecated_algos:
                tasks.append(_task_hsm_rekey(host, algo))
            tasks.append(_task_rotate_certificate(host))
            tasks.append(_task_update_openssl(host, "ml-kem-1024"))
            tasks.append(_task_configure_tls_policy("PQC_HYBRID"))
            tasks.append(_task_nginx_tls_hardening(host))
            tasks.append(_task_enable_hybrid_kem(host))
            tasks.append(_task_verify_pqc_handshake(host))
            effort = 16.0

        elif tier == PlaybookTier.HIGH:
            tasks.append(_task_update_openssl(host, "ml-kem-768"))
            tasks.append(_task_configure_tls_policy("PQC_HYBRID"))
            tasks.append(_task_nginx_tls_hardening(host))
            tasks.append(_task_enable_hybrid_kem(host))
            tasks.append(_task_rotate_certificate(host))
            tasks.append(_task_verify_pqc_handshake(host))
            effort = 8.0

        elif tier == PlaybookTier.MEDIUM:
            tasks.append(_task_enable_hybrid_kem(host))
            tasks.append(_task_configure_tls_policy("PQC_HYBRID"))
            tasks.append(_task_verify_pqc_handshake(host))
            effort = 4.0

        else:  # LOW
            tasks.append(_task_verify_pqc_handshake(host))
            effort = 1.0

        tasks.append(_task_send_notification("{{ playbook_id }}", tier.value))
        return tasks, effort

    def generate(self, result: ComplianceLabelResult) -> list[RemediationPlaybook]:
        """
        Generate one or more Ansible playbooks for a compliance label result.

        Critical-tier playbooks get `approval_status=PENDING` so the approval
        gate can be invoked before execution.

        Returns a list (may be empty if label is FULLY_QUANTUM_SAFE with no deprecated).
        """
        host = result.host or str(result.asset_id or "unknown")
        tier = self._determine_tier(result)

        if tier == PlaybookTier.LOW and result.quantum_label == QuantumLabel.FULLY_QUANTUM_SAFE:
            logger.info("no_playbook_needed", host=host, label=result.quantum_label)
            return []

        tasks, effort = self._build_tasks(host, tier, result.findings)
        algos_targeted = [
            f.algorithm for f in result.findings
            if not f.is_approved or f.is_deprecated
        ]

        approval_status = (
            ApprovalStatus.PENDING if tier == PlaybookTier.CRITICAL else ApprovalStatus.NO_GATE
        )

        playbook = RemediationPlaybook(
            asset_id=result.asset_id,
            host=host,
            tier=tier,
            title=f"PQC Migration — {tier.value.upper()}: {host}",
            description=(
                f"Remediate quantum-vulnerable cryptography on {host}. "
                f"Label: {result.quantum_label.value}. "
                f"Targets: {', '.join(algos_targeted) or 'none'}."
            ),
            algorithms_targeted=algos_targeted,
            ansible_tasks=tasks,
            approval_status=approval_status,
            estimated_effort_hours=effort,
        )

        logger.info(
            "playbook_generated",
            host=host,
            tier=tier.value,
            tasks=len(tasks),
            effort_hours=effort,
            approval=approval_status.value,
        )
        return [playbook]
