"""init

Revision ID: eb36015e5080
Revises: 
Create Date: 2026-04-05 13:13:08.640812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eb36015e5080"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_assets',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate PK — UUIDv4'),
    sa.Column('asset_type', sa.Enum('DOMAIN', 'IP_ADDRESS', 'URL', 'CERTIFICATE', 'API_ENDPOINT', 'LOAD_BALANCER', name='asset_type_enum'), nullable=False),
    sa.Column('asset_value', sa.String(length=2048), nullable=False, comment='The raw asset identifier (FQDN, IPv4/v6, URL …)'),
    sa.Column('organization', sa.String(length=512), nullable=True, comment='Owning organization / business unit'),
    sa.Column('seed_domain', sa.String(length=512), nullable=True, comment='Root domain from which this asset was discovered'),
    sa.Column('status', sa.Enum('PENDING', 'SCANNING', 'SCANNED', 'ERROR', 'EXCLUDED', name='asset_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True, comment='Composite PQC risk score [0.0 – 10.0]'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of labels, e.g. ["internet-facing", "pci-scope"]'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Free-form discovery metadata (Shodan, Amass, Censys …)'),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_scanned', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_value', 'asset_type', name='uq_asset_value_type')
    )
    op.create_index('ix_master_assets_asset_type', 'master_assets', ['asset_type'], unique=False)
    op.create_index('ix_master_assets_metadata_gin', 'master_assets', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('ix_master_assets_risk_score', 'master_assets', ['risk_score'], unique=False)
    op.create_index('ix_master_assets_status', 'master_assets', ['status'], unique=False)
    op.create_table('tls_scan_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('scan_job_id', sa.UUID(), nullable=True, comment='Reference to the Celery task / scan job that produced this result'),
    sa.Column('host', sa.String(length=512), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('highest_tls_version', sa.Enum('SSL_2_0', 'SSL_3_0', 'TLS_1_0', 'TLS_1_1', 'TLS_1_2', 'TLS_1_3', name='tls_version_enum'), nullable=True),
    sa.Column('supports_pqc_kem', sa.Boolean(), nullable=False, comment='True if server negotiated a PQC KEM (e.g. X25519Kyber768)'),
    sa.Column('cipher_suites', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='[{name, key_exchange, auth, symmetric, key_size, pqc_safe}, …]'),
    sa.Column('certificate_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Parsed cert chain: [{subject, issuer, not_after, sig_alg, key_alg, key_size}, …]'),
    sa.Column('leaf_cert_sig_algorithm', sa.String(length=128), nullable=True, comment="e.g. 'sha256WithRSAEncryption', 'ecdsa-with-SHA384'"),
    sa.Column('leaf_cert_key_size', sa.Integer(), nullable=True, comment='RSA modulus bits / EC curve bits of the leaf certificate key'),
    sa.Column('leaf_cert_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='scan_severity_enum'), nullable=False),
    sa.Column('hndl_score', sa.Float(), nullable=True, comment='Harvest-Now-Decrypt-Later risk score [0.0 – 10.0]'),
    sa.Column('vulnerability_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='CVE / advisory IDs discovered during scan'),
    sa.Column('scan_tool', sa.String(length=64), nullable=True, comment="Tool used: 'sslyze', 'zgrab2', 'openssl'"),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Verbatim JSON output from the scanning tool'),
    sa.Column('scan_duration_ms', sa.Integer(), nullable=True, comment='Wall-clock time for this scan in milliseconds'),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['master_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tls_scan_results_asset_id', 'tls_scan_results', ['asset_id'], unique=False)
    op.create_index('ix_tls_scan_results_cipher_suites_gin', 'tls_scan_results', ['cipher_suites'], unique=False, postgresql_using='gin')
    op.create_index('ix_tls_scan_results_hndl_score', 'tls_scan_results', ['hndl_score'], unique=False)
    op.create_index('ix_tls_scan_results_scanned_at', 'tls_scan_results', ['scanned_at'], unique=False)
    op.create_index('ix_tls_scan_results_severity', 'tls_scan_results', ['severity'], unique=False)
    op.create_table('cbom_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('scan_result_id', sa.UUID(), nullable=True, comment='Source TLS scan if this CBOM entry was derived from a TLS scan'),
    sa.Column('algorithm_name', sa.String(length=256), nullable=False, comment="Human-readable name, e.g. 'RSA-2048', 'ECDH-P256', 'ML-KEM-768'"),
    sa.Column('algorithm_oid', sa.String(length=128), nullable=True, comment="ASN.1 OID, e.g. '1.2.840.113549.1.1.1' for RSA"),
    sa.Column('category', sa.Enum('KEY_EXCHANGE', 'DIGITAL_SIGNATURE', 'SYMMETRIC_CIPHER', 'HASH', 'MAC', 'KEY_DERIVATION', 'PRNG', 'CERTIFICATE', 'PROTOCOL', 'OTHER', name='crypto_category_enum'), nullable=False),
    sa.Column('algorithm_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{key_size, curve, padding, iv_size, tag_size, …}'),
    sa.Column('pqc_status', sa.Enum('SAFE', 'HYBRID', 'CLASSICAL', 'DEPRECATED', 'UNKNOWN', name='pqc_status_enum'), nullable=False),
    sa.Column('nist_pqc_level', sa.Integer(), nullable=True, comment='NIST security level (1–5) for PQC algorithms; NULL for classical'),
    sa.Column('quantum_risk_score', sa.Float(), nullable=True, comment='AI-computed quantum vulnerability score [0.0 – 10.0]'),
    sa.Column('cryptographic_strength_bits', sa.Integer(), nullable=True, comment='Classical security strength in bits (e.g. 112 for RSA-2048)'),
    sa.Column('usage_context', sa.String(length=256), nullable=True, comment="Where this algorithm is used: 'tls_handshake', 'jwt_signing', 'db_encryption' …"),
    sa.Column('detection_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='[{tool, method, confidence, timestamp}, …]'),
    sa.Column('replacement_algorithm', sa.String(length=256), nullable=True, comment="Recommended PQC replacement, e.g. 'ML-KEM-768 (CRYSTALS-Kyber)'"),
    sa.Column('migration_complexity', sa.String(length=32), nullable=True, comment="'low' | 'medium' | 'high' | 'critical'"),
    sa.Column('migration_recommendation', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI-generated migration playbook step'),
    sa.Column('cyclonedx_component', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full CycloneDX CBOM component JSON for standards compliance'),
    sa.Column('first_detected', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_confirmed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['master_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_result_id'], ['tls_scan_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'algorithm_oid', 'usage_context', name='uq_cbom_asset_algorithm_context')
    )
    op.create_index('ix_cbom_records_algorithm_parameters_gin', 'cbom_records', ['algorithm_parameters'], unique=False, postgresql_using='gin')
    op.create_index('ix_cbom_records_asset_id', 'cbom_records', ['asset_id'], unique=False)
    op.create_index('ix_cbom_records_category', 'cbom_records', ['category'], unique=False)
    op.create_index('ix_cbom_records_detection_sources_gin', 'cbom_records', ['detection_sources'], unique=False, postgresql_using='gin')
    op.create_index('ix_cbom_records_pqc_status', 'cbom_records', ['pqc_status'], unique=False)
    op.create_index('ix_cbom_records_quantum_risk_score', 'cbom_records', ['quantum_risk_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cbom_records_quantum_risk_score', table_name='cbom_records')
    op.drop_index('ix_cbom_records_pqc_status', table_name='cbom_records')
    op.drop_index('ix_cbom_records_detection_sources_gin', table_name='cbom_records', postgresql_using='gin')
    op.drop_index('ix_cbom_records_category', table_name='cbom_records')
    op.drop_index('ix_cbom_records_asset_id', table_name='cbom_records')
    op.drop_index('ix_cbom_records_algorithm_parameters_gin', table_name='cbom_records', postgresql_using='gin')
    op.drop_table('cbom_records')
    op.drop_index('ix_tls_scan_results_severity', table_name='tls_scan_results')
    op.drop_index('ix_tls_scan_results_scanned_at', table_name='tls_scan_results')
    op.drop_index('ix_tls_scan_results_hndl_score', table_name='tls_scan_results')
    op.drop_index('ix_tls_scan_results_cipher_suites_gin', table_name='tls_scan_results', postgresql_using='gin')
    op.drop_index('ix_tls_scan_results_asset_id', table_name='tls_scan_results')
    op.drop_table('tls_scan_results')
    op.drop_index('ix_master_assets_status', table_name='master_assets')
    op.drop_index('ix_master_assets_risk_score', table_name='master_assets')
    op.drop_index('ix_master_assets_metadata_gin', table_name='master_assets', postgresql_using='gin')
    op.drop_index('ix_master_assets_asset_type', table_name='master_assets')
    op.drop_table('master_assets')
    # ### end Alembic commands ###
